language: ruby
services:
  - redis-server
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database www_rails_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
notifications:
  slack:
    secure: Qi3NqgqqtUb2Sap9LGHphz5achbAOavYke/AgtYgGrrk7qL0EYUmS74quTb4ciWzse/ig4vT5mbBaqLN1hYchK4RUdjBqu9X4VTUsFpHajZ556rXaiws96wbyasvB6/KZrsi/hhJlil7Q1G4SUEJE9Xx3HMBWOtXu0YDMmGhioL50TuPICY+vGLkiYVvvq47YBqHEyW4ZL0PP9rWxA96tPLMwXvK3PjywfZ0yhN0pO9V9d94sCEZ5puTlK6x5Hv6qNJRwLoOwqOGlEExcc0tJ1N/+kRGNAYdJhRILtqNQqybcnfQarezB02CurEmnnSqaSxrcpwA6fgmA18+CaFXF9708c6icb7qe508RruJ7wttfz8HBR/IbnHEvGltd7eKVfH210jlZSBSOcWrrZX5hgAMqKH8sBzLMW8KNUXLgE7iH+C0vlz4RrzNWPL73Kfx4JK3GZwpoW1XB2ssuek65OVwqMXSpsLhLMdc0rwoQgjIAqKKGYrqvNK+438Os4lbsSOyP6OEOM0u2xC4AdoOWWXKTX7kO3hfk249HX5Uih20sBgQ6dqDGeW0tCfdpBe/ocyE+7eQZcVJ5wqbIJtf47qbxyGx/7/D8kR4rN8FJ+9TFz4ysS6C8DRlBIvJvMFd3825ikYIWSVmhrJ4zdTX4zbQe22Mf8LMvBcA8lYLNqE=
env:
  global:
    secure: Y+6WeAxIjQHAOkSIlxoyYF0aAVo6BBip3BHqZevcjEDjG1bsrqVKOVtRBh3M0UkA60KxRn4aTU7QSp0E2UQDxLR7YMPUoq0YoS1d4V7w8c7We++94bZjR1R+jFa7zcn3+WTH9eyEu4gK5e3leOApUJLZ6V3PyGitEQK7GQzQLqHqOqQYykjOEe6CUgrjvXZNsDutyrxWXDQa2N96dqj7lgnkFrJLw4rkJ25WHvps4iIq3aNMXJLBSCtPJGqd/tkdDwbTdeRUtURyZr8tgKaaDWrpVlj8YgUPrKr/lEXr5l4sNhi92rc1OG04lgTSDGERgo6dXjmJPK3f74Hp4nTppbp9Ttosdr7OheiPG5UJmkOGgSxhT3aNkwXSQ55qSySmMJIHBOsQgH9aQcGUfkcpjePDz7WHjx5oKmmuKNCM4cqSYoAHx+fKvJohNWcmgwQH8r8c4L/j5i01OYdpV7UlKAtD2zdYfymtlnYj33RhPwGqT2UtaEk1VX+MZIii/JALSrW6rns+nzaBR1Vn6h4cwATwXpOUupNEqPvZpGkKqkWoEPEZyLzd0mYbWP/3yQnMd4caPKy68CR/o1JhxlPHydrynkGSJ6bXD1pavTZjZyDvxiWfYNCOLaTYQvvnpGZ3Yg5Sz7P4fiobH0guzG8ywwYn62RDsU/oDTGG4vVZ3V8=
