# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b10dd06169f183d022afb5fa4de8a6036cb475972198ab79576ab0664401d1e73f820a9ee520b8a5705746cf526f36da25ccf2f39b61071b0f584da05ca2bbe2

test:
  secret_key_base: 009f71a5e7bfc1c71b6d4db4c7dc3ff0b8209899b0f6af8b861ec7aeb1e357421bd5db2cc400f4794a68bac2d2a891aed0d0c16c98a4709fbe7252f616458a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
